"""empty message

Revision ID: 706f04bd5a4f
Revises: 806a207f5252
Create Date: 2025-11-25 14:13:02.837278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706f04bd5a4f'
down_revision: Union[str, Sequence[str], None] = '806a207f5252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('uploading', 'processing', 'success', 'failed', name='mealstatus'), nullable=False),
    sa.Column('input_type', sa.Enum('audio', 'picture', name='inputtype'), nullable=False),
    sa.Column('input_file_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('foods', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_created_at'), 'meals', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meals_created_at'), table_name='meals')
    op.drop_table('meals')
    # ### end Alembic commands ###
